### ISSUE TITLE
So whats the difference with hitomi?

### ISSUE THREAD

**Issue by masterofobzene** [narumii/HentaiDownloader#2]
You said it needs more dependencies and thats all.
Whats the difference between versions?

**Comment by masterofobzene** [comment]
None of them work btw.

![imagen](https://user-images.githubusercontent.com/94469116/154820681-75e8fdf5-caad-4181-843a-b1adadbb5378.png)

**Comment by masterofobzene** [comment]
![imagen](https://user-images.githubusercontent.com/94469116/154820720-c904e174-95ed-493f-9b2e-b58583e98408.png)


Doesn't work btw. Running latest java.

**Comment by narumii** [comment]
Hitomi version supports https://hitomi.la/ but it's bigger due to dependencies, but i don't linked that HentaiDownloader would be that much bigger in size so i created 2 versions of it.

Your java version is too low. Probably you using java 8 but downloader is written on java 11

**Comment by roobini-gamer** [comment]
> ![imagen](https://user-images.githubusercontent.com/94469116/154820720-c904e174-95ed-493f-9b2e-b58583e98408.png)
> 
> Doesn't work btw. Running latest java.

run in java 11 (in cmd java -jar "downloader.jar"

**Comment by narumii** [comment]
![image](https://user-images.githubusercontent.com/57463654/158029887-cd131d0c-f224-4e00-88bd-117eb4328c55.png)
https://javaalmanac.io/bytecode/versions/
https://stackoverflow.com/questions/9170832/list-of-java-class-file-format-major-version-numbers

**Comment by narumii** [comment]
Welp hitomi version doesn't work and idk if i even wanna bother fixing it.
