### ISSUE TITLE
The folder was created successfully but always downloads in the root dir

### ISSUE THREAD

**Issue by AlexKSera** [narumii/HentaiDownloader#7]
It worked and created a folder where I entered it (D:\NewFolder). When the download started, all the images were placed in the root directory. Both of these happen in CMD & PowerShell

**Comment by DuckEater54** [comment]
I have the same issue, using in this order;
```
LOLI
/home/myname/Documents/porn
rating:explicit blonde_hair blue_eyes cum big_ass incest
10
```
or any alteration of the same command, but with a different representation of the location of the directory I want to download to, either produce no folder and no images, or an empty folder/folder tree

**Comment by narumii** [comment]
https://github.com/narumii/HentaiDownloader/issues/8
